### ISSUE TITLE
Could you give a less basic example?

### ISSUE THREAD

**Issue by tizot** [cnam/security-jwt-service-provider#1]
I tried to use your provider but it doesn't seem to work. I can access every routes whereas I should be redirect to login route or raise an exception maybe.
Here is my code...

``` php
$app['security.jwt'] = array(
     'secret_key' => 'aze123&',
     'life_time'  => 86400, //life time token
     'options' => array(
         'header_name' => 'AUTH-HEADER-TOKEN' //header name for authorisation
     )
);
$app->register(new Silex\Provider\SecurityJWTServiceProvider());
$app['security.firewalls'] = array(
    'login' => array(
        'pattern' => 'login|register|oauth',
        'anonymous' => true,
    ),
    'secured' => array(
        'pattern' => '^.*$',
        'logout' => array('logout_path' => '/users/logout'),
        'users' => array(
            'admin' => array('ROLE_ADMIN', '5FZ2Z8QIkA7UTZ4BYkoC+GsReLf569mSKDsfods6LYQ8t+a8EW9oaircfMpmaLbPBh4FOBiiFyLfuZmTSUwzZg==')
        ),
        'jwt' => array(
            'use_forward' => true,
            'require_previous_session' => false,
            'stateless' => true
        )
    )
);
```

Anyway, thank you for this code I was searching for a looong time !!

**Comment by cnam** [comment]
For correct work.

You must also register

``` php
$app->register(new Silex\Provider\SecurityServiceProvider());
```

and create action for autorization 
**example**

``` php
$app->post('/login', (Request $request) use ($app) {
$vars = $request->request->all();

        try {
            $user = $this->app['users']->loadUserByUsername($vars['_username']);
            if ($this->app['security.encoder.digest']->encodePassword($vars['_password'], '') !== $user->getPassword()) {
                throw new UsernameNotFoundException(sprintf('Username "%s" does not exist.', $vars['_username']));
            } else {
                $response = [
                    'success' => true,
                    'token' => $this->app['security.jwt.encoder']->encode(['name' => $user->getUsername()]),
                ];
            }
        } catch (UsernameNotFoundException $e) {
            $response = [
                'success' => false,
                'error' => 'Invalid credentials',
            ];
        }

        return $this->app->json($response, ($response['success'] == true ? 
                   Response::HTTP_OK :       
                   Response::HTTP_BAD_REQUEST));
}
```

After receiving the token you will need to sign them all requests in headers

AUTH-HEADER-TOKEN: YOUR_PRIVATE_TOKEN

**Comment by cnam** [comment]
As an example you can use this library to look at working on a opensource project 

https://gitlab.com/kanban/backend/tree/master

**Comment by tizot** [comment]
Thank you very much ! It worked !

But I have another problem now ^^
I have a custom UserProvider (with database storage) and some users in my table, with different role values (ROLE_USER or ROLE_USER,ROLE_ADMIN, so I have a role hierarchy). But when I want to check that with $app['security']->isGranted('ROLE_ADMIN') with an authenticated user who has this role, it doesn't work : the test always returns 'false'... 

Does your code fully co-operate with $app['security'] ?

**Comment by cnam** [comment]
Yes it is necessary to supplement the code.
What version Silex you are using?

Most problem is associated with it.

**Comment by tizot** [comment]
Apparently, I'm on the 2.0dev version.

**Comment by cnam** [comment]
Thank you for your issue,  

``` php
$app['security']->isGranted('ROLE_ADMIN')
```

This the code works correctly in new version 0.0.6 or dev-master version

**Comment by tizot** [comment]
You are welcome !
