### ISSUE TITLE
Token Prefix not working

### ISSUE THREAD

**Issue by fjcero** [cnam/security-jwt-service-provider#15]
Hi! I'm testing right now the workflow using the Silex Firewall and it seems broken. In the JWTListener, the option `token_prefix` is missing, so headers like the recommended by JWT are not valid:

```
Authorization: Bearer <token>
```

It works well if I remove the `Bearer` string. Instead of decoding the string directly the lib should remove the token prefix from the Request Header first.

**Comment by cnam** [comment]
Hello @fjcero. It was really a problem. We fixed it in release 1.0.5 for silex 1. \* and 2.0.5 for silex 2. *

**Comment by fjcero** [comment]
@cnam great!
