### ISSUE TITLE
fail to getUsername() on security.token_storage token

### ISSUE THREAD

**Issue by soubok** [cnam/security-jwt-service-provider#16]
Hello,

I try to get the username on a secure route using:
`$app['security.token_storage']->getToken()->getUsername()`

and I get the following error:

```
PHP Notice:  Undefined property: Silex\Component\Security\Http\Token\JWTToken::$usernameClaim in C:\work\web\nova-backoffice\vendor\cnam\security-jwt-service-provider\src\Silex\Component\Security\Http\Token\JWTToken.php on line 60
```

Except for the secret_key and header_name, security.jwt configuration use the default settings.
The secure routes are defined like this:

```
    'secure' => array(
        'pattern' => '^.*$',
        'users' => $app['users'],
        'jwt' => array(
            'use_forward' => true,
            'require_previous_session' => false,
            'stateless' => true,
        )           
    ),
```

Version:

```
        "doctrine/dbal": "^2.5",
        "silex/silex": "~1.3",
        "symfony/security": "~2.7",
        "cnam/security-jwt-service-provider": "1.*"
```

Note that `$token->setUsernameClaim($this->options['username_claim']);` is properly called in `JWTListener.php:65`

Do you need more details, or there is something obvious I am doing wrong ?

**Comment by cnam** [comment]
Hello @soubok we fix this bug in version 1.0.6

**Comment by soubok** [comment]
Thanks, the error does not appear any more, but the getUsername() returns an empty string, should I fill new issue ?

**Comment by cnam** [comment]
What field your are using for encode token:

``` php
$app['security.jwt.encoder']->encode(['name' => $user->getUsername()]);
```

By default getUsername() from getToken() returns "username" from field "name" .

If your are using custom field in jwt token for send username, your must be configure

``` php
$app['security.jwt'] = [
    'options'    => [
        'username_claim' => 'name',
    ]
];
```

**Comment by soubok** [comment]
I use the default field (name)

**Comment by soubok** [comment]
I also noticed that the `public function loadUserByUsername($username)` of the  `UserProviderInterface` is called with the good value for `$username` (when my secure route is called)

ps:
my `$app['security.token_storage']->getToken()->getUsername()` returns null, not an empty string

**Comment by cnam** [comment]
if your need username your must user model and get name from modal.

``` php
$token = $app['security.token_storage']->getToken();

if (null !== $token {
        $user = $token->getUser();
        $username = $user->getUsername();
}
```

**Comment by soubok** [comment]
thank you, it works!

**Comment by soubok** [comment]
And now the last issue for today :)

I try to use the `secure` method of `Silex\Route\SecurityTrait` (see http://silex.sensiolabs.org/doc/providers/security.html#traits) on my secure route:

```
$app->get('/admin', function(Request $request) use($app) {

    return $app->json('ok', 200);
})->secure('ROLE_ADMIN');
```

When I load this route, `loadUserByUsername` is called twice, once with the right `$username` and the second time with `null`

... more simply:
I cannot use `$app['security.authorization_checker']->isGranted('ROLE_ADMIN')` in my route because my `loadUserByUsername` function get `null` as `$username` argument.

**Comment by cnam** [comment]
Hello, try to use version 1.1.0 we add full capability silex security.

**Comment by soubok** [comment]
Thanks, it works !
