### ISSUE TITLE
Critical vulnerabilities in JSON Web Token libraries

### ISSUE THREAD

**Issue by ronanguilloux** [cnam/security-jwt-service-provider#3]
in firebase/php-jwt < 2.0.0
See https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/

**Comment by cnam** [comment]
Release created https://github.com/cnam/security-jwt-service-provider/releases/tag/0.1.0

**Comment by ronanguilloux** [comment]
fixed in #5
